export const MANAGER_PRIMARY_SKILLS = [
  { value: 'mineRate', label: 'Mine Rate' },
  { value: 'shipSpeed', label: 'Ship Speed' },
  { value: 'cargo', label: 'Cargo' },
]

export const PRIMARY_EFFECTS = {
  mineRate: [1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.95],
  shipSpeed: [1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.9],
  cargo: [1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.9],
}

export const MANAGER_SECONDARY_SKILLS = [
  { value: 'empty', label: '— Empty —' },
  { value: 'allMineRate', label: 'All Mine Rate' },
  { value: 'allShipSpeed', label: 'All Ship Speed' },
  { value: 'allCargo', label: 'All Cargo' },
  { value: 'allCraftSpeed', label: 'All Craft Speed' },
  { value: 'allSmeltSpeed', label: 'All Smelt Speed' },
]

export const SECONDARY_EFFECTS = {
  allMineRate: [null, null, 1.05, 1.1, 1.2, 1.3, 1.5],
  allShipSpeed: [null, null, 1.1, 1.2, 1.4, 1.6, 2.0],
  allCargo: [null, null, 1.1, 1.2, 1.4, 1.6, 2.0],
  allCraftSpeed: [null, null, 1.05, 1.1, 1.2, 1.4, 1.7],
  allSmeltSpeed: [null, null, 1.05, 1.1, 1.2, 1.4, 1.7],
}

export const SHIPS = [
  {
    key: 'daughtership',
    label: 'Daughtership',
    bonuses: [{ stat: 'mining', label: 'Mining', mult: 1.5 }],
  },
  {
    key: 'eldership',
    label: 'Eldership',
    bonuses: [
      { stat: 'mining', label: 'Mining', mult: 2.0 },
      { stat: 'craft', label: 'Craft speed', mult: 1.5 },
      { stat: 'smelt', label: 'Smelt speed', mult: 1.5 },
    ],
  },
  {
    key: 'merchantship',
    label: 'Merchantship',
    bonuses: [
      { stat: 'oreValue', label: 'Ore Value', mult: 2.0 },
      { stat: 'alloyValue', label: 'Alloy Value', mult: 2.0 },
      { stat: 'itemValue', label: 'Item Value', mult: 2.0 },
    ],
  },
  {
    key: 'thunderhorse',
    label: 'Thunderhorse',
    bonuses: [
      { stat: 'craft', label: 'Craft speed', mult: 2.0 },
      { stat: 'smelt', label: 'Smelt speed', mult: 2.0 },
    ],
  },
  {
    key: 'aurora',
    label: 'Aurora',
    bonuses: [{ stat: 'manager', label: 'Manager bonuses', mult: 2.0 }],
  },
]

export const SETTINGS_CONFIG = {
  rooms: [
    {
      key: 'engineering',
      label: 'Engineering',
      desc: 'Mine Rate',
      baseEffect: 1.25,
      perLevel: 0.15,
      maxLevel: 60,
    },
    {
      key: 'forge',
      label: 'Forge',
      desc: 'Smelt Speed',
      baseEffect: 1.2,
      perLevel: 0.1,
      maxLevel: 60,
    },
    {
      key: 'workshop',
      label: 'Workshop',
      desc: 'Craft Speed',
      baseEffect: 1.2,
      perLevel: 0.1,
      maxLevel: 60,
    },
    {
      key: 'underforge',
      label: 'Underforge',
      desc: 'Smelting Prices',
      baseEffect: 0.9,
      perLevel: -0.04,
      maxLevel: 11,
    },
    {
      key: 'dorm',
      label: 'Dorms',
      desc: 'Crafting Prices',
      baseEffect: 0.9,
      perLevel: -0.04,
      maxLevel: 11,
    },
    {
      key: 'sales',
      label: 'Sales',
      desc: 'Alloy/Item Values',
      baseEffect: 1.15,
      perLevel: 0.05,
      maxLevel: 60,
    },
    {
      key: 'astronomy',
      label: 'Astronomy',
      desc: 'Planet Upgrade Prices',
      baseEffect: 0.9,
      perLevel: -0.04,
      maxLevel: 11,
    },
    {
      key: 'classroom',
      label: 'Classroom',
      desc: 'Manager Effects',
      baseEffect: 1.15,
      perLevel: 0.05,
      maxLevel: 60,
    },
    {
      key: 'marketing',
      label: 'Marketing',
      desc: 'All positive market change bonuses',
      baseEffect: 1.3,
      perLevel: 0.1,
      maxLevel: 60,
    },
  ],
  projects: [
    { key: 'managerTraining', label: 'Manager Training', desc: 'Manager effects ×1.1', baseEffect: 1.1 },
    { key: 'advancedManagerTraining', label: 'Advanced Manager Training', desc: 'Manager effects ×1.1', baseEffect: 1.1 },
    { key: 'superiorManagerTraining', label: 'Superior Manager Training', desc: 'Manager effects ×1.1', baseEffect: 1.1 },
    { key: 'advancedMining', label: 'Advanced Mining', desc: 'Mine speed ×1.25', baseEffect: 1.25 },
    { key: 'superiorMining', label: 'Superior Mining', desc: 'Mine speed ×1.25', baseEffect: 1.25 },
    {
      key: 'advancedFurnace',
      label: 'Advanced Furnace',
      desc: 'Smelters speed ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'superiorFurnace',
      label: 'Superior Furnace',
      desc: 'Smelters speed ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'advancedCrafter',
      label: 'Advanced Crafter',
      desc: 'Crafters speed ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'superiorCrafter',
      label: 'Superior Crafter',
      desc: 'Crafters speed ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'advancedAlloyValue',
      label: 'Advanced Alloy Value',
      desc: 'Alloy value ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'superiorAlloyValue',
      label: 'Superior Alloy Value',
      desc: 'Alloy value ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'advancedItemValue',
      label: 'Advanced Item Value',
      desc: 'Item value ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'superiorItemValue',
      label: 'Superior Item Value',
      desc: 'Item value ×1.2',
      baseEffect: 1.2,
    },
    {
      key: 'oreTargeting',
      label: 'Ore Targeting',
      desc: 'Most valuable ore on each planet +15% mining',
      baseEffect: 1.15,
    },
    {
      key: 'rover1',
      label: 'Rover Resupply',
      desc: 'Rover mining ×2.5',
      baseEffect: 2.5,
    },
    {
      key: 'rover2',
      label: 'Advanced Rover Resupply',
      desc: 'Rover mining ×2.5 (total ×5)',
      baseEffect: 2.5,
    },
    {
      key: 'smeltingEfficiency',
      label: 'Smelting Efficiency',
      desc: 'Alloy ingredients ×0.8',
      baseEffect: 0.8,
    },
    {
      key: 'craftingEfficiency',
      label: 'Crafting Efficiency',
      desc: 'Item ingredients ×0.8',
      baseEffect: 0.8,
    },
  ],
  beacon: [
    {
      key: 'beacon1_4',
      label: '1-4',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon5_7',
      label: '5-7',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon8_10',
      label: '8-10',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon11_13',
      label: '11-13',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon14_16',
      label: '14-16',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon17_19',
      label: '17-19',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon20_22',
      label: '20-22',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon23_25',
      label: '23-25',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon26_28',
      label: '26-28',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon29_31',
      label: '29-31',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon32_34',
      label: '32-34',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon35_37',
      label: '35-37',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon38_40',
      label: '38-40',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon41_43',
      label: '41-43',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon44_46',
      label: '44-46',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon47_49',
      label: '47-49',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon50_52',
      label: '50-52',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon53_55',
      label: '53-55',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon56_58',
      label: '56-58',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon59_61',
      label: '59-61',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon62_64',
      label: '62-64',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon65_67',
      label: '65-67',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon68_70',
      label: '68-70',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon71_73',
      label: '71-73',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
    {
      key: 'beacon74_76',
      label: '74-76',
      desc: 'Mine rate',
      baseEffect: 1.02,
      perLevel: 0.02,
    },
  ],
  station: [
    {
      key: 'crafting1',
      label: 'Crafting 1',
      desc: 'Craft speed',
      perLevel: 0.01,
      maxLevel: 5,
      costs: [5, 8, 12, 20, 32],
    },
    {
      key: 'crafting2',
      label: 'Crafting 2',
      desc: 'Craft speed',
      perLevel: 0.01,
      maxLevel: 10,
      costs: [6, 8, 11, 16, 23, 32, 45, 63, 88, 123],
    },
    {
      key: 'crafting3',
      label: 'Crafting 3',
      desc: 'Craft speed',
      perLevel: 0.01,
      maxLevel: 15,
      costs: [10, 11, 13, 15, 17, 20, 23, 26, 30, 35, 40, 46, 53, 61, 70],
    },
    {
      key: 'crafting4',
      label: 'Crafting 4',
      desc: 'Craft speed',
      perLevel: 0.02,
      maxLevel: 20,
      costs: [15, 16, 17, 18, 20, 22, 23, 25, 27, 29, 32, 34, 37, 40, 44, 47, 51, 55, 59, 64],
    },
    {
      key: 'crafting5',
      label: 'Crafting 5',
      desc: 'Craft speed',
      perLevel: 0.04,
      maxLevel: 20,
      costs: [30, 30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 44, 45, 46, 48, 49, 51, 52],
    },
    {
      key: 'smelting1',
      label: 'Smelting 1',
      desc: 'Smelt speed',
      perLevel: 0.01,
      maxLevel: 5,
      costs: [5, 8, 12, 20, 32],
    },
    {
      key: 'smelting2',
      label: 'Smelting 2',
      desc: 'Smelt speed',
      perLevel: 0.01,
      maxLevel: 10,
      costs: [6, 8, 11, 16, 23, 32, 45, 63, 88, 123],
    },
    {
      key: 'smelting3',
      label: 'Smelting 3',
      desc: 'Smelt speed',
      perLevel: 0.01,
      maxLevel: 15,
      costs: [10, 11, 13, 15, 17, 20, 23, 26, 30, 35, 40, 46, 53, 61, 70],
    },
    {
      key: 'smelting4',
      label: 'Smelting 4',
      desc: 'Smelt speed',
      perLevel: 0.02,
      maxLevel: 20,
      costs: [15, 16, 17, 18, 20, 22, 23, 25, 27, 29, 32, 34, 37, 40, 44, 47, 51, 55, 59, 64],
    },
    {
      key: 'smelting5',
      label: 'Smelting 5',
      desc: 'Smelt speed',
      perLevel: 0.04,
      maxLevel: 20,
      costs: [30, 30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 41, 42, 44, 45, 46, 48, 49, 51, 52],
    },
    { key: 'mining1', label: 'Mining 1', desc: 'Mine speed', perLevel: 0.02, maxLevel: 4, costs: [5, 10, 21, 43] },
    {
      key: 'mining2',
      label: 'Mining 2',
      desc: 'Mine speed',
      perLevel: 0.1,
      maxLevel: 25,
      costs: [26, 28, 31, 34, 37, 40, 44, 48, 53, 58, 63, 69, 76, 83, 91, 100, 109, 119, 131, 143, 156, 171, 187, 205, 224],
    },
    { key: 'miningGlobal', label: 'Global 1.2x', desc: 'Mine speed ×1.2', baseEffect: 1.2 },
    {
      key: 'alloyItem1',
      label: 'Alloy & Item 1',
      desc: 'Alloy & Item value',
      perLevel: 0.036,
      maxLevel: 5,
      costs: [10, 12, 15, 19, 23],
    },
    {
      key: 'alloyItem2',
      label: 'Alloy & Item 2',
      desc: 'Alloy & Item value',
      perLevel: 0.08,
      maxLevel: 5,
      costs: [50, 54, 58, 62, 68],
    },
    {
      key: 'alloyItem3',
      label: 'Alloy & Item 3',
      desc: 'Alloy & Item value',
      perLevel: 0.08,
      maxLevel: 5,
      costs: [50, 54, 58, 62, 68],
    },
    {
      key: 'alloyItem4',
      label: 'Alloy & Item 4',
      desc: 'Alloy & Item value',
      perLevel: 0.02,
      maxLevel: 4,
      costs: [100, 110, 121, 133],
    },
    {
      key: 'alloyItem5',
      label: 'Alloy & Item 5',
      desc: 'Alloy & Item value',
      perLevel: 0.02,
      maxLevel: 4,
      costs: [100, 110, 121, 133],
    },
    {
      key: 'alloyItem6',
      label: 'Alloy & Item 6',
      desc: 'Alloy & Item value',
      perLevel: 0.075,
      maxLevel: 2,
      costs: [200, 205],
    },
    {
      key: 'alloyItem7',
      label: 'Alloy & Item 7',
      desc: 'Alloy & Item value',
      perLevel: 0.075,
      maxLevel: 2,
      costs: [200, 205],
    },
    {
      key: 'market1',
      label: 'Market 1',
      desc: 'Market value',
      perLevel: 0.04,
      maxLevel: 5,
      costs: [10, 12, 15, 19, 23],
    },
    {
      key: 'market2',
      label: 'Market 2',
      desc: 'Market value',
      perLevel: 0.05,
      maxLevel: 5,
      costs: [50, 54, 58, 62, 68],
    },
    {
      key: 'market3',
      label: 'Market 3',
      desc: 'Market value',
      perLevel: 0.05,
      maxLevel: 5,
      costs: [50, 54, 58, 62, 68],
    },
    {
      key: 'market4',
      label: 'Market 4',
      desc: 'Market value',
      perLevel: 0.05,
      maxLevel: 4,
      costs: [100, 110, 121, 133],
    },
    {
      key: 'market5',
      label: 'Market 5',
      desc: 'Market value',
      perLevel: 0.05,
      maxLevel: 4,
      costs: [100, 110, 121, 133],
    },
    {
      key: 'market6',
      label: 'Market 6',
      desc: 'Market value',
      perLevel: 0.175,
      maxLevel: 2,
      costs: [200, 205],
    },
    {
      key: 'market7',
      label: 'Market 7',
      desc: 'Market value',
      perLevel: 0.175,
      maxLevel: 2,
      costs: [200, 205],
    },
    {
      key: 'manager1',
      label: 'Manager 1',
      desc: 'Manager effects',
      perLevel: 0.012,
      maxLevel: 5,
      costs: [15, 15, 15, 16, 16],
    },
    {
      key: 'manager2',
      label: 'Manager 2',
      desc: 'Manager effects',
      perLevel: 0.055,
      maxLevel: 4,
      costs: [250, 275, 302, 332],
    },
    {
      key: 'manager3',
      label: 'Manager 3',
      desc: 'Manager effects',
      perLevel: 0.055,
      maxLevel: 4,
      costs: [250, 275, 302, 332],
    },
    {
      key: 'manager4',
      label: 'Manager 4',
      desc: 'Manager effects',
      perLevel: 0.005,
      maxLevel: 4,
      costs: [30, 39, 53, 70],
    },
    {
      key: 'manager5',
      label: 'Manager 5',
      desc: 'Manager effects',
      perLevel: 0.005,
      maxLevel: 6,
      costs: [25, 33, 44, 58, 78, 104],
    },
    {
      key: 'manager6',
      label: 'Manager 6',
      desc: 'Manager effects',
      perLevel: 0.005,
      maxLevel: 8,
      costs: [20, 26, 35, 47, 62, 83, 110, 147],
    },
    { key: 'manager7', label: 'Manager 7', desc: 'Manager effects', perLevel: 0.06, maxLevel: 1, costs: [600] },
    {
      key: 'manager8',
      label: 'Manager 8',
      desc: 'Manager effects',
      perLevel: 0.005,
      maxLevel: 10,
      costs: [15, 19, 26, 35, 46, 62, 83, 110, 146, 195],
    },
    {
      key: 'planetCost1',
      label: 'Planet Cost 1',
      desc: 'Planet upgrade cost reduction',
      kind: 'reduce',
      perLevel: 0.5,
      maxLevel: 1,
      costs: [150],
    },
    {
      key: 'planetCost2',
      label: 'Planet Cost 2',
      desc: 'Planet upgrade cost reduction',
      kind: 'reduce',
      perLevel: 0.25,
      maxLevel: 2,
      costs: [75, 75],
    },
    {
      key: 'planetCost3',
      label: 'Planet Cost 3',
      desc: 'Planet upgrade cost reduction',
      kind: 'reduce',
      perLevel: 0.5,
      maxLevel: 3,
      costs: [100, 160, 256],
    },
    {
      key: 'planetCost4',
      label: 'Planet Cost 4',
      desc: 'Planet upgrade cost reduction',
      kind: 'reduce',
      perLevel: 0.5,
      maxLevel: 4,
      costs: [150, 157, 165, 173],
    },
    {
      key: 'planetCost5',
      label: 'Planet Cost 5',
      desc: 'Planet upgrade cost reduction',
      kind: 'reduce',
      perLevel: 0.75,
      maxLevel: 4,
      costs: [230, 241, 253, 266],
    },
  ],
  managers: [],
}

export const STATION_GROUPS = [
  {
    name: 'Planets',
    subsections: [
      { name: 'Mining', keys: ['mining1', 'mining2'] },
      {
        name: 'Planet Cost',
        keys: ['planetCost1', 'planetCost2', 'planetCost3', 'planetCost4', 'planetCost5'],
      },
    ],
  },
  { name: 'Crafting', keys: ['crafting1', 'crafting2', 'crafting3', 'crafting4', 'crafting5'] },
  { name: 'Smelting', keys: ['smelting1', 'smelting2', 'smelting3', 'smelting4', 'smelting5'] },
  {
    name: 'Alloy & Item',
    keys: [
      'alloyItem1',
      'alloyItem2',
      'alloyItem3',
      'alloyItem4',
      'alloyItem5',
      'alloyItem6',
      'alloyItem7',
    ],
  },
  { name: 'Market', keys: ['market1', 'market2', 'market3', 'market4', 'market5', 'market6', 'market7'] },
  {
    name: 'Manager',
    keys: ['manager1', 'manager2', 'manager3', 'manager4', 'manager5', 'manager6', 'manager7', 'manager8'],
  },
]

export const MARKET_VALS = [0.33, 0.5, 1, 2, 3, 4, 5]
